//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escademy {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Escademy.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apex legends is the hottest Battle Royal game to hit the gaming scene. For you to excel in the game, it’s crucial you learn the guns and understand each unique legend and their abilities. With these abilities, you can build your reputation and be among the few experts in the game.
        ///Try our Apex Legends coaching service and start winning. Our experienced coaches will help you build on your strengths so you can get kills and carry your team to a deserved victory..
        /// </summary>
        public static string Apex_Description {
            get {
                return ResourceManager.GetString("Apex_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter-Strike: Global Offensive is one of the most fast-paced, breathtaking and competitive team FPS games in the industry. If you’re looking to improve your counter strike skills or choose the right loadout under pressure, our professional Counter-Strike coaches are here to help you. Your gaming experience doesn’t matter, with E-Sport Academy; you’ve got something to learn..
        /// </summary>
        public static string CSGO_Description {
            get {
                return ResourceManager.GetString("CSGO_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is one of the most intense, most played E-sports games. You need skills in tweaking hero builds, winning your lane, pushing down towers amongst others, if you wish to dominate ranked players. Just like in any competitive game, all levels of players can get stuck and unable to progress further in the game. This is where our DotA2 coaching services come in.
        ///Our coaches are experienced in the game and will help you navigate your way to the top of the list of experts in DotA2. They’re not just gamers but  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dota2_Description {
            get {
                return ResourceManager.GetString("Dota2_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have talent and would love to connect with similar minds all around the world?
        ///You can leverage our E-Sport Academy to connect, network and learn new skills from pro players all around the world. We are packing the best E-Sport coaches and pro players in the world..
        /// </summary>
        public static string DoYouHaveTalentCareer {
            get {
                return ResourceManager.GetString("DoYouHaveTalentCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Sport Academy.
        /// </summary>
        public static string ESportAcademy {
            get {
                return ResourceManager.GetString("ESportAcademy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand your Network.
        /// </summary>
        public static string ExpandNetwork {
            get {
                return ResourceManager.GetString("ExpandNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Sport Academy&apos;s purpose is to create a platform for passionate e-sport players who would like to develop themselves.
        ///Maybe your goal is to become the best amongst your friends, or go all-in and try to join the competitive scene.
        ///All this requires education and learning which is why we created E-Sport academy! We have coaches from around the world who is extraordinarily high level gamers.
        ///Our values is quality over quantity so our customers gets the best possible service on the market!.
        /// </summary>
        public static string FooterAboutUs {
            get {
                return ResourceManager.GetString("FooterAboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string FooterAboutUsTitle {
            get {
                return ResourceManager.GetString("FooterAboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string FooterContactUsTitle {
            get {
                return ResourceManager.GetString("FooterContactUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute.
        /// </summary>
        public static string FooterContributeTitle {
            get {
                return ResourceManager.GetString("FooterContributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string FooterPrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("FooterPrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sitemap.
        /// </summary>
        public static string FooterSitemapTitle {
            get {
                return ResourceManager.GetString("FooterSitemapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortnite is a new online battle royale survival game introduced in 2017. Though new, it has attracted more than 100 million players in less than 2 years. As a new game, people are still figuring it all out so this could be the perfect opportunity for you to step up your game and be among the few experts. 
        ///When you start building your Fortnite reputation early on, you can become one of the best players in the E-Sport industry. Our experienced Fortnite coaches are there to guide you through the high-energy a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Fortnite_Description {
            get {
                return ResourceManager.GetString("Fortnite_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow us on Twitter.
        /// </summary>
        public static string HeaderFollowUsTwitter {
            get {
                return ResourceManager.GetString("HeaderFollowUsTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us on Discord.
        /// </summary>
        public static string HeaderJoinUsDiscord {
            get {
                return ResourceManager.GetString("HeaderJoinUsDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like us onFacebook.
        /// </summary>
        public static string HeaderLikeUsFB {
            get {
                return ResourceManager.GetString("HeaderLikeUsFB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vi hjælper dig med at skabe et netværk af andre lige så passioneret spillere som dig..
        /// </summary>
        public static string HelpCreateNetwork {
            get {
                return ResourceManager.GetString("HelpCreateNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to League of legends, one of the most popular and extremely competitive online battle arena, has many aspects and approaches to it. The game can be overwhelming and challenging to navigate through to the top, but don’t worry, our league of legends coaching service has got you covered.
        ///Our extensively experienced and dedicated LoL coaches will provide you with bespoke lessons depending on your playing level. If you’re aiming to reach your goal, our coaches will use their knowledge and skills to get you there..
        /// </summary>
        public static string LoL_Description {
            get {
                return ResourceManager.GetString("LoL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string MenuAdministration {
            get {
                return ResourceManager.GetString("MenuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coaches.
        /// </summary>
        public static string MenuCoaches {
            get {
                return ResourceManager.GetString("MenuCoaches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rediger Profil.
        /// </summary>
        public static string MenuEditProfile {
            get {
                return ResourceManager.GetString("MenuEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forside.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string MenuLogin {
            get {
                return ResourceManager.GetString("MenuLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log af.
        /// </summary>
        public static string MenuLogout {
            get {
                return ResourceManager.GetString("MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil.
        /// </summary>
        public static string MenuProfile {
            get {
                return ResourceManager.GetString("MenuProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teams.
        /// </summary>
        public static string MenuTeams {
            get {
                return ResourceManager.GetString("MenuTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the growth in E-Sports, gamers all around the world are looking to improve, and pro players are eager to coach gamers to become world class E-Sports game players. 
        ///
        ///We offer coaching services in different games, by well-experienced coaches. Our coaches are not just any coach; they’re professionals who have passed our rigorous application process and are experienced in both gaming and teaching. Go through our games, make your choice and get started immediately. A coach is waiting for you!.
        /// </summary>
        public static string offeredVariedCoachingCategories {
            get {
                return ResourceManager.GetString("offeredVariedCoachingCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Started!.
        /// </summary>
        public static string OverviewOfSpeedCourses {
            get {
                return ResourceManager.GetString("OverviewOfSpeedCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The E-Sport industry is tough and only the skilled and diligent excel. With our online game coaching platform at your disposal, you’re ahead, and there’s no turning back to failure. Pick your favorite game, pick a coach and start your journey to becoming the best in the world..
        /// </summary>
        public static string ReachSuccess_JourneyPro {
            get {
                return ResourceManager.GetString("ReachSuccess_JourneyPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyrights Reserved by .
        /// </summary>
        public static string RightsReservedBy {
            get {
                return ResourceManager.GetString("RightsReservedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Be the first to review us on.
        /// </summary>
        public static string TrustpilotFirstReview {
            get {
                return ResourceManager.GetString("TrustpilotFirstReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        public static string TrustpilotReviewCount {
            get {
                return ResourceManager.GetString("TrustpilotReviewCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online E-Sport coaching!.
        /// </summary>
        public static string variedCoaching {
            get {
                return ResourceManager.GetString("variedCoaching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To be the best in this game, you should understand your game level and all the essential aspects of the game. The game is stressful for new players and requires constant maintenance of high concentration and extended ability to deal with unknown and challenging situations.
        ///Never to worry; our coaches are experts that are successful as competitive WoW players and are eager to give you important advice and insights that will immensely improve your performance..
        /// </summary>
        public static string Wow_Description {
            get {
                return ResourceManager.GetString("Wow_Description", resourceCulture);
            }
        }
    }
}
