//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escademy.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EscademyMDB : DbContext
    {
        public EscademyMDB()
            : base("name=EscademyMDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<esc_accounts> esc_accounts { get; set; }
        public virtual DbSet<esc_chat> esc_chat { get; set; }
        public virtual DbSet<esc_games> esc_games { get; set; }
        public virtual DbSet<esc_languages> esc_languages { get; set; }
        public virtual DbSet<esc_orders> esc_orders { get; set; }
        public virtual DbSet<esc_serviceTypes> esc_serviceTypes { get; set; }
        public virtual DbSet<esc_Transactions> esc_Transactions { get; set; }
        public virtual DbSet<esc_verificationcodes> esc_verificationcodes { get; set; }
        public virtual DbSet<esc_profilelanguages> esc_profilelanguages { get; set; }
        public virtual DbSet<esc_userpasswordreset> esc_userpasswordreset { get; set; }
        public virtual DbSet<esc_wallet> esc_wallet { get; set; }
        public virtual DbSet<esc_profileTrophies> esc_profileTrophies { get; set; }
        public virtual DbSet<esc_profilegames> esc_profilegames { get; set; }
        public virtual DbSet<esc_faq> esc_faq { get; set; }
        public virtual DbSet<esc_profilegamesFiles> esc_profilegamesFiles { get; set; }
        public virtual DbSet<esc_profilegamesPricing> esc_profilegamesPricing { get; set; }
        public virtual DbSet<esc_profilegamesRating> esc_profilegamesRating { get; set; }
    }
}
