//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escademy.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class esc_userpasswordreset
    {
        public int Id { get; set; }
        public string PasswordResetToken { get; set; }
        public System.DateTime PasswordResetExpiration { get; set; }
        public string Email { get; set; }
    }
}
