//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escademy.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class esc_orders
    {
        public int Id { get; set; }
        public string txn_id { get; set; }
        public decimal mc_gross { get; set; }
        public string mc_currency { get; set; }
        public int quantity { get; set; }
        public string payer_email { get; set; }
        public int payer_account_id { get; set; }
        public int receiver_id { get; set; }
        public int game_id { get; set; }
        public bool success { get; set; }
        public System.DateTime date { get; set; }
        public string order_status { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public int review_stars { get; set; }
        public string review_comments { get; set; }
    }
}
