//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escademy.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class esc_wallet
    {
        public int Id { get; set; }
        public Nullable<int> accountId { get; set; }
        public Nullable<decimal> wallet_amount { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public Nullable<System.DateTime> updated_date { get; set; }
        public Nullable<decimal> TotalWithdrawn { get; set; }
    }
}
