//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escademy.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class esc_chat
    {
        public long Id { get; set; }
        public int Sender_Id { get; set; }
        public int Receiver_id { get; set; }
        public string Message { get; set; }
        public int Status { get; set; }
        public System.DateTime Created_at { get; set; }
    }
}
